sonar.projectKey=TheRedHatter_vulnado_46c354c5-c5c0-4894-880b-717ecb24f710
# No compiled classes available for Java analysis; exclude .java from analysis to allow scan to complete.
sonar.exclusions=**/*.java
